name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## What changed

  $CHANGES

categories:
  - title: "Features"
    labels: ["enhancement", "feature"]
  - title: "Bug fixes"
    labels: ["bug", "fix"]
  - title: "Installation and packaging"
    labels: ["installation", "packaging"]
  - title: "Documentation"
    labels: ["documentation"]

version-resolver:
  default: patch
  major:
    labels: ["major"]
  minor:
    labels: ["enhancement", "feature"]
  patch:
    labels: ["bug", "documentation", "installation", "packaging"]
